### ISSUE TITLE
The documentation and example page are not working (anymore)

### ISSUE THREAD

**Issue by robbinjanssen** [tjwebb/react-bootstrap-select#1]
I've tried implementing your react-bootstrap-select package, but was unable to do so.
Was looking for some more examples and documentation, but the link in the readme is dead.

**Comment by tjwebb** [comment]
Yea, that link is irrelevant and I should remove it from the README. The short example in the README should be all you need. Then you can customize with all these options: http://silviomoreto.github.io/bootstrap-select/.

Are you experiencing a specific issue/error that I can help with?

**Comment by tjwebb** [comment]
btw I updated the README with a working link. Thanks for pointing that out.

**Comment by robbinjanssen** [comment]
Not yet, thanks for updating! Issue resolved ;-)
