### ISSUE TITLE
Npm install of react-bootstrap-select fails

### ISSUE THREAD

**Issue by mawhidby** [tjwebb/react-bootstrap-select#3]
npm install fails with message:

> react-bootstrap-select@0.13.0 postinstall /Users/bpmadmin/dev/alchemy/update-service-gui/redblack-ui/node_modules/react-bootstrap-select
> jsx jsx/ dist/
> 
> could not open file: jsx/, Error: EISDIR, illegal operation on a directory
> 
> npm ERR! Darwin 14.3.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "react-bootstrap-select"
> npm ERR! node v0.12.2
> npm ERR! npm  v2.7.4
> npm ERR! code ELIFECYCLE
> 
> npm ERR! react-bootstrap-select@0.13.0 postinstall: `jsx jsx/ dist/`
> npm ERR! Exit status 65
> npm ERR! 
> npm ERR! Failed at the react-bootstrap-select@0.13.0 postinstall script 'jsx jsx/ dist/'.
> npm ERR! This is most likely a problem with the react-bootstrap-select package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     jsx jsx/ dist/
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls react-bootstrap-select
> npm ERR! There is likely additional logging output above.

Seen this issue on both Mac OS X (10.10.3) and Windows 7

**Comment by mawhidby** [comment]
Gist of npm-debug.log available here: https://gist.githubusercontent.com/mawhidby/43c9913d93d525a804c0/raw/npm-debug.log

**Comment by diffractometer** [comment]
This is happening to me as well
