### ISSUE TITLE
none of the events are not working

### ISSUE THREAD

**Issue by sridharAJ** [tjwebb/react-bootstrap-select#4]
I want to get selected values onChange event

**Comment by AlexKovalevych** [comment]
Try something like this in your component's componentDidMount method:

``` javascript
$(ReactDOM.findDOMNode(this.refs.yourselect)).find('select').selectpicker().on('change', function(){
    console.log($(this).val());
});
```

Not sure if it works with 0.13, but definitely it is with react 0.14, see https://github.com/tjwebb/react-bootstrap-select/pull/10
